// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GoConnectDB(arg1:string):Promise<string>;

export function GoOperateDB(arg1:string,arg2:string):Promise<any>;

export function GoPingDB(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;
