// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GoConnectDB(arg1) {
  return window['go']['main']['App']['GoConnectDB'](arg1);
}

export function GoOperateDB(arg1, arg2) {
  return window['go']['main']['App']['GoOperateDB'](arg1, arg2);
}

export function GoPingDB(arg1) {
  return window['go']['main']['App']['GoPingDB'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
